[package]
authors = ["Philipp Hansch <dev@phansch.net>"]
edition = "2018"
name = "webdriver-install"
version = "0.1.0"
[dependencies]
eyre = "*"
reqwest = { version = "0.11", features = ["blocking"] }
