[package]
authors = ["Philipp Hansch <dev@phansch.net>"]
edition = "2018"
name = "webdriver-install"
version = "0.1.0"
[dependencies]
eyre = "*"
sys-info = "*"

[dependencies.reqwest]
features = ["blocking"]
version = "0.11"
