name: GitHub Release
on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: uploads

      # Upload release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          files: webdriver-install*

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set GIT_TAG env
        run: echo "GIT_TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      # Build linux64 release
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename file
        run: cd target/release && mv webdriver_install webdriver-install
      - name: Create archive
        run: cd target/release && tar -czvf webdriver-install-$GIT_TAG-linux64.tar.gz webdriver-install

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uploads
          path: target/release/webdriver-install*.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set GIT_TAG env
        run: echo ("GIT_TAG=" + $env:GITHUB_REF.replace('refs/tags/', '')) >> $env:GITHUB_ENV

      # Build win64 release
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename file
        run: cd target/release && mv webdriver_install.exe webdriver-install.exe
      - name: Create archive
        run: cd target/release && powershell Compress-Archive webdriver-install.exe "webdriver-install-${{ env.GIT_TAG }}-win64.zip"

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uploads
          path: target/release/webdriver-install*.zip

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set GIT_TAG env
        run: echo "GIT_TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      # Build macos release
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename file
        run: cd target/release && mv webdriver_install webdriver-install
      - name: Create archive
        run: cd target/release && tar -czvf webdriver-install-$GIT_TAG-macos.tar.gz webdriver-install

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uploads
          path: target/release/webdriver-install*.tar.gz
